# Describes the format for available jriver services

add_to_playlist:
  target:
    entity:
      integration: jriver
      domain: media_player
  fields:
    query:
      example: "[Album Artist (auto)]=[AIR] ~sort=[Date],[Album],[Track #]"
      selector:
        text:
    playlist_path:
      example: Alarms\Morning\Wakeup
      selector:
        text:

seek_relative:
  target:
    entity:
      integration: jriver
      domain: media_player
  fields:
    seek_duration:
      example: -5
      selector:
        number:

adjust_volume:
  target:
    entity:
      integration: jriver
      domain: media_player
  fields:
    delta:
      example: -5
      selector:
        number:
          min: -100
          max: 100

activate_zone:
  target:
    entity:
      integration: jriver
      domain: remote
  fields:
    zone_name:
      required: true
      example: Player
      selector:
        text:

send_mcc:
  target:
    entity:
      integration: jriver
      domain: remote
  fields:
    command:
      required: true
      example: 22000
      selector:
        number:
          min: 10000
          max: 40000
    parameter:
      example: 2
      selector:
        number:
    block:
      default: true
      selector:
        boolean:
    zone_name:
      example: Player
      selector:
        text:

wake:
  fields:
    entity_id:
      example: "remote.mcserver"
      required: true
      selector:
        entity:
          integration: jriver
          domain: remote
